## 0. Create Spark session

In [1]:
import os
from pyspark.sql import SparkSession
from pyspark import SparkConf
from pyspark import SparkContext

os.environ['PYSPARK_SUBMIT_ARGS'] = (
    '--packages org.apache.hadoop:hadoop-aws:3.2.0,org.apache.hadoop:hadoop-common:3.2.0,io.trino:trino-jdbc:422 '
    'pyspark-shell'
)
os.environ['S3_ENDPOINT'] = "http://minio:9000"
os.environ['AWS_ACCESS_KEY_ID'] = "minio"
os.environ['AWS_SECRET_ACCESS_KEY'] = "minio123"

spark = (
    SparkSession.builder
    .appName("spark-read-minio")
    .config("spark.hadoop.fs.s3a.access.key", os.getenv("AWS_ACCESS_KEY_ID"))
    .config("spark.hadoop.fs.s3a.secret.key", os.getenv("AWS_SECRET_ACCESS_KEY"))
    .config("spark.hadoop.fs.s3a.endpoint", os.getenv("S3_ENDPOINT"))
    .config("spark.hadoop.fs.s3a.connection.ssl.enabled", "false")
    .config("spark.hadoop.fs.s3a.path.style.access", "true")
    .config("spark.hadoop.fs.s3a.attempts.maximum", "1")
    .config("spark.hadoop.fs.s3a.connection.establish.timeout", "5000")
    .config("spark.hadoop.fs.s3a.connection.timeout", "10000")
    .getOrCreate()
)
spark.sparkContext.setLogLevel("WARN")

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.apache.spark.unsafe.Platform (file:/usr/local/spark-3.1.2-bin-hadoop3.2/jars/spark-unsafe_2.12-3.1.2.jar) to constructor java.nio.DirectByteBuffer(long,int)
WARNING: Please consider reporting this to the maintainers of org.apache.spark.unsafe.Platform
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

:: loading settings :: url = jar:file:/usr/local/spark-3.1.2-bin-hadoop3.2/jars/ivy-2.4.0.jar!/org/apache/ivy/core/settings/ivysettings.xml

Ivy Default Cache set to: /home/jovyan/.ivy2/cache
The jars for the packages stored in: /home/jovyan/.ivy2/jars
org.apache.hadoop#hadoop-aws added as a dependency
org.apache.hadoop#hadoop-common added as a dependency
io.trino#trino-jdbc added as a dependency
:: resolving dependencies :: org.apache.spark#spark-submit-parent-963d46b6-01e0-49e8-a8b9-8a9b94891e62;1.0
	confs: [default]
	found org.apache.hadoop#hadoop-aws;3.2.0 in central
	found com.amazonaws#aws-java-sdk-bundle;1.11.375 in central
	found org.apache.hadoop#hadoop-common;3.2.0 in central
	found org.apache.hadoop#hadoop-annotations;3.2.0 in central
	found com.google.guava#guava;11.0.2 in central
	found com.google.code.findbugs#jsr305;3.0.0 in central
	found commons-cli#commons-cli;1.2 in central
	found org.apache.commons#commons-math3;3.1.1 in central
	found org.apache.httpcomponents#httpclient;4.5.2 in central
	found org.apache.httpcomponents#httpcore;4.4.4 in central
	found commons-logging#commons-logging;1.1.3 in central
	found commons-codec#commons-codec;1.11 in central
	found commons-io#commons-io;2.5 in central
	found commons-net#commons-net;3.6 in central
	found commons-collections#commons-collections;3.2.2 in central
	found javax.servlet#javax.servlet-api;3.1.0 in central
	found org.eclipse.jetty#jetty-server;9.3.24.v20180605 in central
	found org.eclipse.jetty#jetty-http;9.3.24.v20180605 in central
	found org.eclipse.jetty#jetty-util;9.3.24.v20180605 in central
	found org.eclipse.jetty#jetty-io;9.3.24.v20180605 in central
	found org.eclipse.jetty#jetty-servlet;9.3.24.v20180605 in central
	found org.eclipse.jetty#jetty-security;9.3.24.v20180605 in central
	found org.eclipse.jetty#jetty-webapp;9.3.24.v20180605 in central
	found org.eclipse.jetty#jetty-xml;9.3.24.v20180605 in central
	found com.sun.jersey#jersey-core;1.19 in central
	found javax.ws.rs#jsr311-api;1.1.1 in central
	found com.sun.jersey#jersey-servlet;1.19 in central
	found com.sun.jersey#jersey-json;1.19 in central
	found org.codehaus.jettison#jettison;1.1 in central
	found com.sun.xml.bind#jaxb-impl;2.2.3-1 in central
	found javax.xml.bind#jaxb-api;2.2.11 in central
	found org.codehaus.jackson#jackson-core-asl;1.9.13 in central
	found org.codehaus.jackson#jackson-mapper-asl;1.9.13 in central
	found org.codehaus.jackson#jackson-jaxrs;1.9.13 in central
	found org.codehaus.jackson#jackson-xc;1.9.13 in central
	found com.sun.jersey#jersey-server;1.19 in central
	found log4j#log4j;1.2.17 in central
	found commons-beanutils#commons-beanutils;1.9.3 in central
	found org.apache.commons#commons-configuration2;2.1.1 in central
	found org.apache.commons#commons-lang3;3.7 in central
	found org.apache.commons#commons-text;1.4 in central
	found org.slf4j#slf4j-api;1.7.25 in central
	found org.slf4j#slf4j-log4j12;1.7.25 in central
	found org.apache.avro#avro;1.7.7 in central
	found com.thoughtworks.paranamer#paranamer;2.3 in central
	found org.xerial.snappy#snappy-java;1.0.5 in central
	found org.apache.commons#commons-compress;1.4.1 in central
	found org.tukaani#xz;1.0 in central
	found com.google.re2j#re2j;1.1 in central
	found com.google.protobuf#protobuf-java;2.5.0 in central
	found com.google.code.gson#gson;2.2.4 in central
	found org.apache.hadoop#hadoop-auth;3.2.0 in central
	found com.nimbusds#nimbus-jose-jwt;4.41.1 in central
	found com.github.stephenc.jcip#jcip-annotations;1.0-1 in central
	found net.minidev#json-smart;2.3 in central
	found net.minidev#accessors-smart;1.2 in central
	found org.ow2.asm#asm;5.0.4 in central
	found org.apache.zookeeper#zookeeper;3.4.13 in central
	found jline#jline;0.9.94 in central
	found org.apache.yetus#audience-annotations;0.5.0 in central
	found io.netty#netty;3.10.5.Final in central
	found org.apache.curator#curator-framework;2.12.0 in central
	found org.apache.curator#curator-client;2.12.0 in central
	found org.apache.kerby#kerb-simplekdc;1.0.1 in central
	found org.apache.kerby#kerb-client;1.0.1 in central
	found org.apache.kerby#kerby-config;1.0.1 in central
	found org.apache.kerby#kerb-core;1.0.1 in central
	found org.apache.kerby#kerby-pkix;1.0.1 in central
	found org.apache.kerby#kerby-asn1;1.0.1 in central
	found org.apache.kerby#kerby-util;1.0.1 in central
	found org.apache.kerby#kerb-common;1.0.1 in central
	found org.apache.kerby#kerb-crypto;1.0.1 in central
	found org.apache.kerby#kerb-util;1.0.1 in central
	found org.apache.kerby#token-provider;1.0.1 in central
	found org.apache.kerby#kerb-admin;1.0.1 in central
	found org.apache.kerby#kerb-server;1.0.1 in central
	found org.apache.kerby#kerb-identity;1.0.1 in central
	found org.apache.kerby#kerby-xdr;1.0.1 in central
	found com.jcraft#jsch;0.1.54 in central
	found org.apache.curator#curator-recipes;2.12.0 in central
	found org.apache.htrace#htrace-core4;4.1.0-incubating in central
	found com.fasterxml.jackson.core#jackson-databind;2.9.5 in central
	found com.fasterxml.jackson.core#jackson-annotations;2.9.5 in central
	found com.fasterxml.jackson.core#jackson-core;2.9.5 in central
	found org.codehaus.woodstox#stax2-api;3.1.4 in central
	found com.fasterxml.woodstox#woodstox-core;5.0.3 in central
	found dnsjava#dnsjava;2.1.7 in central
	found javax.servlet.jsp#jsp-api;2.1 in central
	found io.trino#trino-jdbc;422 in central
:: resolution report :: resolve 2308ms :: artifacts dl 118ms
	:: modules in use:
	com.amazonaws#aws-java-sdk-bundle;1.11.375 from central in [default]
	com.fasterxml.jackson.core#jackson-annotations;2.9.5 from central in [default]
	com.fasterxml.jackson.core#jackson-core;2.9.5 from central in [default]
	com.fasterxml.jackson.core#jackson-databind;2.9.5 from central in [default]
	com.fasterxml.woodstox#woodstox-core;5.0.3 from central in [default]
	com.github.stephenc.jcip#jcip-annotations;1.0-1 from central in [default]
	com.google.code.findbugs#jsr305;3.0.0 from central in [default]
	com.google.code.gson#gson;2.2.4 from central in [default]
	com.google.guava#guava;11.0.2 from central in [default]
	com.google.protobuf#protobuf-java;2.5.0 from central in [default]
	com.google.re2j#re2j;1.1 from central in [default]
	com.jcraft#jsch;0.1.54 from central in [default]
	com.nimbusds#nimbus-jose-jwt;4.41.1 from central in [default]
	com.sun.jersey#jersey-core;1.19 from central in [default]
	com.sun.jersey#jersey-json;1.19 from central in [default]
	com.sun.jersey#jersey-server;1.19 from central in [default]
	com.sun.jersey#jersey-servlet;1.19 from central in [default]
	com.sun.xml.bind#jaxb-impl;2.2.3-1 from central in [default]
	com.thoughtworks.paranamer#paranamer;2.3 from central in [default]
	commons-beanutils#commons-beanutils;1.9.3 from central in [default]
	commons-cli#commons-cli;1.2 from central in [default]
	commons-codec#commons-codec;1.11 from central in [default]
	commons-collections#commons-collections;3.2.2 from central in [default]
	commons-io#commons-io;2.5 from central in [default]
	commons-logging#commons-logging;1.1.3 from central in [default]
	commons-net#commons-net;3.6 from central in [default]
	dnsjava#dnsjava;2.1.7 from central in [default]
	io.netty#netty;3.10.5.Final from central in [default]
	io.trino#trino-jdbc;422 from central in [default]
	javax.servlet#javax.servlet-api;3.1.0 from central in [default]
	javax.servlet.jsp#jsp-api;2.1 from central in [default]
	javax.ws.rs#jsr311-api;1.1.1 from central in [default]
	javax.xml.bind#jaxb-api;2.2.11 from central in [default]
	jline#jline;0.9.94 from central in [default]
	log4j#log4j;1.2.17 from central in [default]
	net.minidev#accessors-smart;1.2 from central in [default]
	net.minidev#json-smart;2.3 from central in [default]
	org.apache.avro#avro;1.7.7 from central in [default]
	org.apache.commons#commons-compress;1.4.1 from central in [default]
	org.apache.commons#commons-configuration2;2.1.1 from central in [default]
	org.apache.commons#commons-lang3;3.7 from central in [default]
	org.apache.commons#commons-math3;3.1.1 from central in [default]
	org.apache.commons#commons-text;1.4 from central in [default]
	org.apache.curator#curator-client;2.12.0 from central in [default]
	org.apache.curator#curator-framework;2.12.0 from central in [default]
	org.apache.curator#curator-recipes;2.12.0 from central in [default]
	org.apache.hadoop#hadoop-annotations;3.2.0 from central in [default]
	org.apache.hadoop#hadoop-auth;3.2.0 from central in [default]
	org.apache.hadoop#hadoop-aws;3.2.0 from central in [default]
	org.apache.hadoop#hadoop-common;3.2.0 from central in [default]
	org.apache.htrace#htrace-core4;4.1.0-incubating from central in [default]
	org.apache.httpcomponents#httpclient;4.5.2 from central in [default]
	org.apache.httpcomponents#httpcore;4.4.4 from central in [default]
	org.apache.kerby#kerb-admin;1.0.1 from central in [default]
	org.apache.kerby#kerb-client;1.0.1 from central in [default]
	org.apache.kerby#kerb-common;1.0.1 from central in [default]
	org.apache.kerby#kerb-core;1.0.1 from central in [default]
	org.apache.kerby#kerb-crypto;1.0.1 from central in [default]
	org.apache.kerby#kerb-identity;1.0.1 from central in [default]
	org.apache.kerby#kerb-server;1.0.1 from central in [default]
	org.apache.kerby#kerb-simplekdc;1.0.1 from central in [default]
	org.apache.kerby#kerb-util;1.0.1 from central in [default]
	org.apache.kerby#kerby-asn1;1.0.1 from central in [default]
	org.apache.kerby#kerby-config;1.0.1 from central in [default]
	org.apache.kerby#kerby-pkix;1.0.1 from central in [default]
	org.apache.kerby#kerby-util;1.0.1 from central in [default]
	org.apache.kerby#kerby-xdr;1.0.1 from central in [default]
	org.apache.kerby#token-provider;1.0.1 from central in [default]
	org.apache.yetus#audience-annotations;0.5.0 from central in [default]
	org.apache.zookeeper#zookeeper;3.4.13 from central in [default]
	org.codehaus.jackson#jackson-core-asl;1.9.13 from central in [default]
	org.codehaus.jackson#jackson-jaxrs;1.9.13 from central in [default]
	org.codehaus.jackson#jackson-mapper-asl;1.9.13 from central in [default]
	org.codehaus.jackson#jackson-xc;1.9.13 from central in [default]
	org.codehaus.jettison#jettison;1.1 from central in [default]
	org.codehaus.woodstox#stax2-api;3.1.4 from central in [default]
	org.eclipse.jetty#jetty-http;9.3.24.v20180605 from central in [default]
	org.eclipse.jetty#jetty-io;9.3.24.v20180605 from central in [default]
	org.eclipse.jetty#jetty-security;9.3.24.v20180605 from central in [default]
	org.eclipse.jetty#jetty-server;9.3.24.v20180605 from central in [default]
	org.eclipse.jetty#jetty-servlet;9.3.24.v20180605 from central in [default]
	org.eclipse.jetty#jetty-util;9.3.24.v20180605 from central in [default]
	org.eclipse.jetty#jetty-webapp;9.3.24.v20180605 from central in [default]
	org.eclipse.jetty#jetty-xml;9.3.24.v20180605 from central in [default]
	org.ow2.asm#asm;5.0.4 from central in [default]
	org.slf4j#slf4j-api;1.7.25 from central in [default]
	org.slf4j#slf4j-log4j12;1.7.25 from central in [default]
	org.tukaani#xz;1.0 from central in [default]
	org.xerial.snappy#snappy-java;1.0.5 from central in [default]
	---------------------------------------------------------------------
	|                  |            modules            ||   artifacts   |
	|       conf       | number| search|dwnlded|evicted|| number|dwnlded|
	---------------------------------------------------------------------
	|      default     |   89  |   0   |   0   |   0   ||   88  |   0   |
	---------------------------------------------------------------------
:: retrieving :: org.apache.spark#spark-submit-parent-963d46b6-01e0-49e8-a8b9-8a9b94891e62
	confs: [default]
	0 artifacts copied, 88 already retrieved (0kB/35ms)
24/11/04 13:59:11 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).

## 1. Extract from object storage

In [2]:
from pyspark.sql import functions as F

silver_path = "s3a://velib/silver/velib-disponibilite-en-temps-reel"
df_silver = spark.read.parquet(silver_path)

# Date de coupure + filtre
date_coupure = "2024-10-31"
df_silver = df_silver.filter(F.col("duedate") >= date_coupure)

# Vérifications
print("Schema:")
df_silver.printSchema()
print("\nSample data:")
df_silver.show(5, truncate=False)
print("\nTotal records:", df_silver.count())

24/11/04 13:59:15 WARN MetricsConfig: Cannot locate configuration: tried hadoop-metrics2-s3a-file-system.properties,hadoop-metrics2.properties

Schema:
root
 |-- capacity: long (nullable = true)
 |-- duedate: string (nullable = true)
 |-- ebike: long (nullable = true)
 |-- is_installed: string (nullable = true)
 |-- is_renting: string (nullable = true)
 |-- is_returning: string (nullable = true)
 |-- mechanical: long (nullable = true)
 |-- name: string (nullable = true)
 |-- nom_arrondissement_communes: string (nullable = true)
 |-- numbikesavailable: long (nullable = true)
 |-- numdocksavailable: long (nullable = true)
 |-- stationcode: string (nullable = true)
 |-- fill_ratio: double (nullable = true)
 |-- part_minute: string (nullable = true)
 |-- lat: double (nullable = true)
 |-- lon: double (nullable = true)
 |-- part_day: date (nullable = true)


Sample data:

+--------+-------------------------+-----+------------+----------+------------+----------+-----------------------------+---------------------------+-----------------+-----------------+-----------+--------------------+----------------+------------------+------------------+----------+
|capacity|duedate                  |ebike|is_installed|is_renting|is_returning|mechanical|name                         |nom_arrondissement_communes|numbikesavailable|numdocksavailable|stationcode|fill_ratio          |part_minute     |lat               |lon               |part_day  |
+--------+-------------------------+-----+------------+----------+------------+----------+-----------------------------+---------------------------+-----------------+-----------------+-----------+--------------------+----------------+------------------+------------------+----------+
|21      |2024-10-31T09:46:08+00:00|1    |OUI         |OUI       |OUI         |0         |Toudouze - Clauzel           |Paris                      |1                |20               |9020       |0.047619047619047616|2024-10-31T09:46|48.87929591733507 |2.3373600840568547|2024-10-31|
|35      |2024-10-31T10:01:28+00:00|8    |OUI         |OUI       |OUI         |1         |Benjamin Godard - Victor Hugo|Paris                      |9                |26               |16107      |0.2571428571428571  |2024-10-31T10:01|48.865983         |2.275725          |2024-10-31|
|25      |2024-10-31T09:52:41+00:00|5    |OUI         |OUI       |OUI         |8         |Cassini - Denfert-Rochereau  |Paris                      |13               |10               |14111      |0.52                |2024-10-31T09:52|48.837525839067   |2.3360354080796   |2024-10-31|
|20      |2024-10-31T09:53:44+00:00|3    |OUI         |OUI       |OUI         |9         |Rouget de L'isle - Watteau   |Vitry-sur-Seine            |12               |8                |44015      |0.6                 |2024-10-31T09:53|48.778192750803   |2.3963020229163   |2024-10-31|
|12      |2024-10-31T09:51:04+00:00|4    |OUI         |OUI       |OUI         |6         |Messine - Place Du Pérou     |Paris                      |10               |1                |8026       |0.8333333333333334  |2024-10-31T09:51|48.875448033960744|2.315508019010038 |2024-10-31|
+--------+-------------------------+-----+------------+----------+------------+----------+-----------------------------+---------------------------+-----------------+-----------------+-----------+--------------------+----------------+------------------+------------------+----------+
only showing top 5 rows

Total records: 475870

## 2. Transform

In [3]:
from pyspark.sql import functions as F
from pyspark.sql.window import Window

df_silver = df_silver.filter(F.col("stationcode").isNotNull())
df_silver = df_silver.withColumn("timestamp", F.to_timestamp("duedate"))
df_silver = df_silver.withColumn("hour", F.date_format("timestamp", "yyyy-MM-dd HH:00:00"))
window_station = Window.partitionBy("stationcode").orderBy("timestamp")

# Calcul du turnover rate (départ/arrivé): compte +1 pour chaque arrivée et +1 pour chaque départ
df_turnover = df_silver.withColumn(
    "arrivals", F.when(F.col("numbikesavailable") > F.lag("numbikesavailable", 1).over(window_station), 
                      F.col("numbikesavailable") - F.lag("numbikesavailable", 1).over(window_station)).otherwise(0)
)

df_turnover = df_turnover.withColumn(
    "departures", F.when(F.col("numbikesavailable") < F.lag("numbikesavailable", 1).over(window_station), 
                         F.lag("numbikesavailable", 1).over(window_station) - F.col("numbikesavailable")).otherwise(0)
)

# Turnover rate total : somme des arrivées et des départs
df_turnover = df_turnover.withColumn("date", F.substring(F.col("duedate"), 1, 10)).groupBy("stationcode", "hour", "date").agg(
    F.sum("arrivals").alias("total_arrivals"),
    F.sum("departures").alias("total_departures"),
    (F.sum("arrivals") + F.sum("departures")).alias("total_turnover_rate"),
    F.first("name").alias("station_name"),     
    F.first("capacity").alias("station_capacity"),
    F.last("numbikesavailable", ignorenulls=True).alias("numbikesavailable")
)

# Affichage du résultat
df_turnover.select("stationcode", "hour", "date", "total_arrivals", "total_departures", "total_turnover_rate", "station_capacity", "station_name").limit(30).toPandas()

,stationcode,hour,date,total_arrivals,total_departures,total_turnover_rate,station_capacity,station_name
0,26005,2024-10-31 07:00:00,2024-10-31,11,8,19,30,Hôtel de Ville d'Asnières sur Seine
1,26005,2024-10-31 09:00:00,2024-10-31,29,31,60,30,Hôtel de Ville d'Asnières sur Seine
2,26005,2024-10-31 11:00:00,2024-10-31,0,4,4,30,Hôtel de Ville d'Asnières sur Seine
3,26005,2024-10-31 12:00:00,2024-10-31,8,12,20,30,Hôtel de Ville d'Asnières sur Seine
4,26005,2024-10-31 13:00:00,2024-10-31,7,6,13,30,Hôtel de Ville d'Asnières sur Seine
5,30002,2024-10-31 07:00:00,2024-10-31,0,0,0,40,Jean Rostand - Paul Vaillant Couturier
6,30002,2024-10-31 09:00:00,2024-10-31,16,17,33,40,Jean Rostand - Paul Vaillant Couturier
7,30002,2024-10-31 11:00:00,2024-10-31,0,3,3,40,Jean Rostand - Paul Vaillant Couturier
8,30002,2024-10-31 12:00:00,2024-10-31,2,3,5,40,Jean Rostand - Paul Vaillant Couturier
9,30002,2024-10-31 13:00:00,2024-10-31,7,6,13,40,Jean Rostand - Paul Vaillant Couturier
10,35004,2024-10-31 07:00:00,2024-10-31,6,11,17,60,Place du Président Salvador Allende
11,35004,2024-10-31 09:00:00,2024-10-31,4,4,8,60,Place du Président Salvador Allende
12,35004,2024-10-31 10:00:00,2024-10-31,5,5,10,60,Place du Président Salvador Allende
13,35004,2024-10-31 11:00:00,2024-10-31,0,1,1,60,Place du Président Salvador Allende
14,35004,2024-10-31 12:00:00,2024-10-31,9,12,21,60,Place du Président Salvador Allende
15,35004,2024-10-31 13:00:00,2024-10-31,7,4,11,60,Place du Président Salvador Allende
16,9009,2024-10-31 07:00:00,2024-10-31,9,12,21,21,Square Montholon
17,9009,2024-10-31 09:00:00,2024-10-31,19,19,38,21,Square Montholon
18,9009,2024-10-31 10:00:00,2024-10-31,16,17,33,21,Square Montholon
19,9009,2024-10-31 11:00:00,2024-10-31,0,4,4,21,Square Montholon
20,9009,2024-10-31 12:00:00,2024-10-31,5,4,9,21,Square Montholon
21,9009,2024-10-31 13:00:00,2024-10-31,6,6,12,21,Square Montholon
22,15052,2024-10-31 07:00:00,2024-10-31,11,17,28,48,Convention - Vaugirard
23,15052,2024-10-31 09:00:00,2024-10-31,19,23,42,48,Convention - Vaugirard
24,15052,2024-10-31 10:00:00,2024-10-31,27,23,50,48,Convention - Vaugirard
25,15052,2024-10-31 11:00:00,2024-10-31,4,0,4,48,Convention - Vaugirard
26,15052,2024-10-31 12:00:00,2024-10-31,8,11,19,48,Convention - Vaugirard
27,15052,2024-10-31 13:00:00,2024-10-31,14,12,26,48,Convention - Vaugirard
28,2110,2024-10-31 07:00:00,2024-10-31,57,39,96,28,Jeûneurs - Mulhouse
29,2110,2024-10-31 09:00:00,2024-10-31,23,21,44,28,Jeûneurs - Mulhouse

In [4]:
# Calcul des statistiques sur l'ensemble des stations par plage de temps
stats_global = df_silver.withColumn("date", F.substring(F.col("duedate"), 1, 10)).groupBy("hour").agg(
    F.avg("numbikesavailable").alias("mean_available"),
    F.expr("percentile(numbikesavailable, 0.5)").alias("median_available"),
    F.min("numbikesavailable").alias("min_available"),
    F.max("numbikesavailable").alias("max_available")
)


# Affichage
print("Statistiques globales par plage de temps :")
stats_global.limit(30).toPandas()  #.show(truncate=False)

Statistiques globales par plage de temps :

,hour,mean_available,median_available,min_available,max_available
0,2024-10-31 10:00:00,16.029145,13.0,0,66
1,2024-10-31 07:00:00,11.571198,9.0,0,65
2,2024-10-31 11:00:00,11.967318,9.0,0,65
3,2024-10-31 09:00:00,10.783099,7.0,0,65
4,2024-10-31 13:00:00,12.174249,8.0,0,66
5,2024-10-31 12:00:00,12.064662,9.0,0,66
6,2024-10-31 06:00:00,0.322581,0.0,0,1
7,2024-10-31 08:00:00,3.662614,2.0,0,20

In [5]:
# Calcul des statistiques par station par heure
stats_station = (
    df_silver
    .withColumn("date", F.substring(F.col("duedate"), 1, 10))
    .groupBy("stationcode", "hour")
    .agg(
        F.avg("numbikesavailable").alias("mean_available"),
        F.expr("percentile_approx(numbikesavailable, 0.5)").alias("median_available"),  # Correction ici
        F.min("numbikesavailable").alias("min_available"),
        F.max("numbikesavailable").alias("max_available"),
        F.first("name").alias("name")
    )
)

# Affichage des statistiques par station
print("Statistiques par station par heure :")
stats_station.limit(20).toPandas()

Statistiques par station par heure :

,stationcode,hour,mean_available,median_available,min_available,max_available,name
0,10113,2024-10-31 10:00:00,2.505882,3,1,5,Parmentier - Hôpital Saint-Louis
1,1016,2024-10-31 10:00:00,18.576471,19,17,20,Thérèse - Opéra
2,11004,2024-10-31 12:00:00,26.911111,24,24,31,Charonne - Faubourg Saint-Antoine
3,11014,2024-10-31 11:00:00,17.000000,17,17,17,Place de la Nation - Taillebourg
4,11037,2024-10-31 11:00:00,25.000000,25,25,25,Faubourg Du Temple - Republique
5,11112,2024-10-31 11:00:00,5.000000,5,5,5,Jules Vallès - Charonne
6,12027,2024-10-31 09:00:00,8.863636,9,6,10,Montgallet - Charenton
7,12040,2024-10-31 13:00:00,16.700000,17,14,18,Porte de Charenton
8,12123,2024-10-31 09:00:00,23.361702,24,16,27,Château de Vincennes
9,13103,2024-10-31 09:00:00,21.000000,21,19,23,Hôpital Pitié Salpêtrière
10,14132,2024-10-31 11:00:00,3.000000,3,3,3,Bézout - Général Leclerc
11,15011,2024-10-31 12:00:00,32.622222,31,31,35,Cambronne - Villa Croix Nivert
12,15047,2024-10-31 13:00:00,4.166667,4,4,5,Morillons - Dantzig
13,15050,2024-10-31 12:00:00,3.755556,1,1,7,Dominique Pado - Croix Nivert
14,16020,2024-10-31 07:00:00,5.838710,9,1,9,Place de la Porte de Passy
15,17003,2024-10-31 07:00:00,12.758065,17,4,17,Jacques Kellner - Saint-Ouen
16,17030,2024-10-31 13:00:00,3.500000,4,2,5,Pereire - Rennequin
17,17037,2024-10-31 13:00:00,4.533333,5,3,6,Bayen - Pereire
18,17039,2024-10-31 09:00:00,3.969697,4,2,8,Place Saint-Ferdinand
19,17126,2024-10-31 11:00:00,22.000000,22,22,22,Hélène et François Missoffe - Emile Borel

## 3. Load into object storage

In [6]:
os.environ['S3_OUTPUT_PATH'] = "s3a://velib/gold/velib-disponibilite-en-temps-reel"

df_turnover.printSchema()

# Création de hour_start selon le type de hour
if df_turnover.schema["hour"].dataType.simpleString() == "struct":
    df_turnover = df_turnover.withColumn("hour_start", F.col("hour.start"))
else:
    df_turnover = df_turnover.withColumn("hour_start", F.col("hour"))  

df_turnover = df_turnover.withColumn("hour_start", F.to_timestamp(F.col("hour_start")))
stats_global = stats_global.withColumn("hour_start", F.col("hour.start") if df_turnover.schema["hour"].dataType.simpleString() == "struct" else F.col("hour"))

df_turnover = df_turnover.drop("hour")
stats_global = stats_global.drop("hour")
stats_station = stats_station.drop("hour")

# Ecriture des df dans minio
# turnover
(
    df_turnover.write
    .partitionBy("hour_start")  
    .format("parquet")
    .mode("overwrite")
    .save(f"{os.getenv('S3_OUTPUT_PATH')}/turnover")
)

# statistiques globales
(
    stats_global.write
    .partitionBy("hour_start")
    .format("parquet")
    .mode("overwrite")
    .save(f"{os.getenv('S3_OUTPUT_PATH')}/stats_global")
)

#statistiques par stations
(
    stats_station.write
    .partitionBy("name")
    .format("parquet")
    .mode("overwrite")
    .save(f"{os.getenv('S3_OUTPUT_PATH')}/stats_station")
)

df_parquet = spark.read.parquet(f"{os.getenv('S3_OUTPUT_PATH')}/stats_station")
df_parquet.printSchema()

root
 |-- stationcode: string (nullable = true)
 |-- hour: string (nullable = true)
 |-- date: string (nullable = true)
 |-- total_arrivals: long (nullable = true)
 |-- total_departures: long (nullable = true)
 |-- total_turnover_rate: long (nullable = true)
 |-- station_name: string (nullable = true)
 |-- station_capacity: long (nullable = true)
 |-- numbikesavailable: long (nullable = true)

24/11/04 13:59:46 WARN MemoryManager: Total allocation exceeds 95.00% (1,020,054,720 bytes) of heap memory
Scaling row group sizes to 95.00% for 8 writers
24/11/04 13:59:46 WARN MemoryManager: Total allocation exceeds 95.00% (1,020,054,720 bytes) of heap memory
Scaling row group sizes to 84.44% for 9 writers
24/11/04 13:59:46 WARN MemoryManager: Total allocation exceeds 95.00% (1,020,054,720 bytes) of heap memory
Scaling row group sizes to 76.00% for 10 writers
24/11/04 13:59:46 WARN MemoryManager: Total allocation exceeds 95.00% (1,020,054,720 bytes) of heap memory
Scaling row group sizes to 69.09% for 11 writers
24/11/04 13:59:46 WARN MemoryManager: Total allocation exceeds 95.00% (1,020,054,720 bytes) of heap memory
Scaling row group sizes to 63.33% for 12 writers
24/11/04 13:59:46 WARN MemoryManager: Total allocation exceeds 95.00% (1,020,054,720 bytes) of heap memory
Scaling row group sizes to 58.46% for 13 writers
24/11/04 13:59:46 WARN MemoryManager: Total allocation exceeds 95.00% (1,020,054,720 bytes) of heap memory
Scaling row group sizes to 54.29% for 14 writers
24/11/04 13:59:46 WARN MemoryManager: Total allocation exceeds 95.00% (1,020,054,720 bytes) of heap memory
Scaling row group sizes to 50.67% for 15 writers
24/11/04 13:59:46 WARN MemoryManager: Total allocation exceeds 95.00% (1,020,054,720 bytes) of heap memory
Scaling row group sizes to 47.50% for 16 writers
24/11/04 13:59:46 WARN MemoryManager: Total allocation exceeds 95.00% (1,020,054,720 bytes) of heap memory
Scaling row group sizes to 50.67% for 15 writers
24/11/04 13:59:46 WARN MemoryManager: Total allocation exceeds 95.00% (1,020,054,720 bytes) of heap memory
Scaling row group sizes to 54.29% for 14 writers
24/11/04 13:59:46 WARN MemoryManager: Total allocation exceeds 95.00% (1,020,054,720 bytes) of heap memory
Scaling row group sizes to 58.46% for 13 writers
24/11/04 13:59:46 WARN MemoryManager: Total allocation exceeds 95.00% (1,020,054,720 bytes) of heap memory
Scaling row group sizes to 63.33% for 12 writers
24/11/04 13:59:46 WARN MemoryManager: Total allocation exceeds 95.00% (1,020,054,720 bytes) of heap memory
Scaling row group sizes to 69.09% for 11 writers
24/11/04 13:59:46 WARN MemoryManager: Total allocation exceeds 95.00% (1,020,054,720 bytes) of heap memory
Scaling row group sizes to 76.00% for 10 writers
24/11/04 13:59:46 WARN MemoryManager: Total allocation exceeds 95.00% (1,020,054,720 bytes) of heap memory
Scaling row group sizes to 84.44% for 9 writers
24/11/04 13:59:46 WARN MemoryManager: Total allocation exceeds 95.00% (1,020,054,720 bytes) of heap memory
Scaling row group sizes to 95.00% for 8 writers
24/11/04 13:59:46 WARN MemoryManager: Total allocation exceeds 95.00% (1,020,054,720 bytes) of heap memory
Scaling row group sizes to 95.00% for 8 writers
24/11/04 13:59:46 WARN MemoryManager: Total allocation exceeds 95.00% (1,020,054,720 bytes) of heap memory
Scaling row group sizes to 84.44% for 9 writers
24/11/04 13:59:46 WARN MemoryManager: Total allocation exceeds 95.00% (1,020,054,720 bytes) of heap memory
Scaling row group sizes to 76.00% for 10 writers
24/11/04 13:59:46 WARN MemoryManager: Total allocation exceeds 95.00% (1,020,054,720 bytes) of heap memory
Scaling row group sizes to 84.44% for 9 writers
24/11/04 13:59:46 WARN MemoryManager: Total allocation exceeds 95.00% (1,020,054,720 bytes) of heap memory
Scaling row group sizes to 95.00% for 8 writers
24/11/04 13:59:46 WARN MemoryManager: Total allocation exceeds 95.00% (1,020,054,720 bytes) of heap memory
Scaling row group sizes to 84.44% for 9 writers
24/11/04 13:59:46 WARN MemoryManager: Total allocation exceeds 95.00% (1,020,054,720 bytes) of heap memory
Scaling row group sizes to 95.00% for 8 writers
24/11/04 13:59:46 WARN MemoryManager: Total allocation exceeds 95.00% (1,020,054,720 bytes) of heap memory
Scaling row group sizes to 84.44% for 9 writers
24/11/04 13:59:46 WARN MemoryManager: Total allocation exceeds 95.00% (1,020,054,720 bytes) of heap memory
Scaling row group sizes to 76.00% for 10 writers
24/11/04 13:59:46 WARN MemoryManager: Total allocation exceeds 95.00% (1,020,054,720 bytes) of heap memory
Scaling row group sizes to 69.09% for 11 writers
24/11/04 13:59:46 WARN MemoryManager: Total allocation exceeds 95.00% (1,020,054,720 bytes) of heap memory
Scaling row group sizes to 63.33% for 12 writers
24/11/04 13:59:46 WARN MemoryManager: Total allocation exceeds 95.00% (1,020,054,720 bytes) of heap memory
Scaling row group sizes to 58.46% for 13 writers
24/11/04 13:59:46 WARN MemoryManager: Total allocation exceeds 95.00% (1,020,054,720 bytes) of heap memory
Scaling row group sizes to 54.29% for 14 writers
24/11/04 13:59:46 WARN MemoryManager: Total allocation exceeds 95.00% (1,020,054,720 bytes) of heap memory
Scaling row group sizes to 50.67% for 15 writers
24/11/04 13:59:46 WARN MemoryManager: Total allocation exceeds 95.00% (1,020,054,720 bytes) of heap memory
Scaling row group sizes to 54.29% for 14 writers
24/11/04 13:59:46 WARN MemoryManager: Total allocation exceeds 95.00% (1,020,054,720 bytes) of heap memory
Scaling row group sizes to 50.67% for 15 writers
24/11/04 13:59:46 WARN MemoryManager: Total allocation exceeds 95.00% (1,020,054,720 bytes) of heap memory
Scaling row group sizes to 54.29% for 14 writers
24/11/04 13:59:46 WARN MemoryManager: Total allocation exceeds 95.00% (1,020,054,720 bytes) of heap memory
Scaling row group sizes to 58.46% for 13 writers
24/11/04 13:59:46 WARN MemoryManager: Total allocation exceeds 95.00% (1,020,054,720 bytes) of heap memory
Scaling row group sizes to 63.33% for 12 writers
24/11/04 13:59:46 WARN MemoryManager: Total allocation exceeds 95.00% (1,020,054,720 bytes) of heap memory
Scaling row group sizes to 69.09% for 11 writers
24/11/04 13:59:46 WARN MemoryManager: Total allocation exceeds 95.00% (1,020,054,720 bytes) of heap memory
Scaling row group sizes to 76.00% for 10 writers
24/11/04 13:59:46 WARN MemoryManager: Total allocation exceeds 95.00% (1,020,054,720 bytes) of heap memory
Scaling row group sizes to 84.44% for 9 writers
24/11/04 13:59:46 WARN MemoryManager: Total allocation exceeds 95.00% (1,020,054,720 bytes) of heap memory
Scaling row group sizes to 95.00% for 8 writers
24/11/04 13:59:46 WARN MemoryManager: Total allocation exceeds 95.00% (1,020,054,720 bytes) of heap memory
Scaling row group sizes to 95.00% for 8 writers
24/11/04 13:59:46 WARN MemoryManager: Total allocation exceeds 95.00% (1,020,054,720 bytes) of heap memory
Scaling row group sizes to 95.00% for 8 writers
24/11/04 13:59:46 WARN MemoryManager: Total allocation exceeds 95.00% (1,020,054,720 bytes) of heap memory
Scaling row group sizes to 84.44% for 9 writers
24/11/04 13:59:46 WARN MemoryManager: Total allocation exceeds 95.00% (1,020,054,720 bytes) of heap memory
Scaling row group sizes to 95.00% for 8 writers
24/11/04 13:59:46 WARN MemoryManager: Total allocation exceeds 95.00% (1,020,054,720 bytes) of heap memory
Scaling row group sizes to 84.44% for 9 writers
24/11/04 13:59:46 WARN MemoryManager: Total allocation exceeds 95.00% (1,020,054,720 bytes) of heap memory
Scaling row group sizes to 76.00% for 10 writers
24/11/04 13:59:46 WARN MemoryManager: Total allocation exceeds 95.00% (1,020,054,720 bytes) of heap memory
Scaling row group sizes to 69.09% for 11 writers
24/11/04 13:59:46 WARN MemoryManager: Total allocation exceeds 95.00% (1,020,054,720 bytes) of heap memory
Scaling row group sizes to 63.33% for 12 writers
24/11/04 13:59:46 WARN MemoryManager: Total allocation exceeds 95.00% (1,020,054,720 bytes) of heap memory
Scaling row group sizes to 58.46% for 13 writers
24/11/04 13:59:46 WARN MemoryManager: Total allocation exceeds 95.00% (1,020,054,720 bytes) of heap memory
Scaling row group sizes to 63.33% for 12 writers
24/11/04 13:59:46 WARN MemoryManager: Total allocation exceeds 95.00% (1,020,054,720 bytes) of heap memory
Scaling row group sizes to 69.09% for 11 writers
24/11/04 13:59:46 WARN MemoryManager: Total allocation exceeds 95.00% (1,020,054,720 bytes) of heap memory
Scaling row group sizes to 63.33% for 12 writers
24/11/04 13:59:46 WARN MemoryManager: Total allocation exceeds 95.00% (1,020,054,720 bytes) of heap memory
Scaling row group sizes to 58.46% for 13 writers
24/11/04 13:59:46 WARN MemoryManager: Total allocation exceeds 95.00% (1,020,054,720 bytes) of heap memory
Scaling row group sizes to 63.33% for 12 writers
24/11/04 13:59:46 WARN MemoryManager: Total allocation exceeds 95.00% (1,020,054,720 bytes) of heap memory
Scaling row group sizes to 69.09% for 11 writers
24/11/04 13:59:46 WARN MemoryManager: Total allocation exceeds 95.00% (1,020,054,720 bytes) of heap memory
Scaling row group sizes to 76.00% for 10 writers
24/11/04 13:59:46 WARN MemoryManager: Total allocation exceeds 95.00% (1,020,054,720 bytes) of heap memory
Scaling row group sizes to 69.09% for 11 writers
24/11/04 13:59:46 WARN MemoryManager: Total allocation exceeds 95.00% (1,020,054,720 bytes) of heap memory
Scaling row group sizes to 63.33% for 12 writers
24/11/04 13:59:46 WARN MemoryManager: Total allocation exceeds 95.00% (1,020,054,720 bytes) of heap memory
Scaling row group sizes to 58.46% for 13 writers
24/11/04 13:59:46 WARN MemoryManager: Total allocation exceeds 95.00% (1,020,054,720 bytes) of heap memory
Scaling row group sizes to 63.33% for 12 writers
24/11/04 13:59:47 WARN MemoryManager: Total allocation exceeds 95.00% (1,020,054,720 bytes) of heap memory
Scaling row group sizes to 69.09% for 11 writers
24/11/04 13:59:47 WARN MemoryManager: Total allocation exceeds 95.00% (1,020,054,720 bytes) of heap memory
Scaling row group sizes to 76.00% for 10 writers
24/11/04 13:59:47 WARN MemoryManager: Total allocation exceeds 95.00% (1,020,054,720 bytes) of heap memory
Scaling row group sizes to 84.44% for 9 writers
24/11/04 13:59:47 WARN MemoryManager: Total allocation exceeds 95.00% (1,020,054,720 bytes) of heap memory
Scaling row group sizes to 76.00% for 10 writers
24/11/04 13:59:47 WARN MemoryManager: Total allocation exceeds 95.00% (1,020,054,720 bytes) of heap memory
Scaling row group sizes to 84.44% for 9 writers
24/11/04 13:59:47 WARN MemoryManager: Total allocation exceeds 95.00% (1,020,054,720 bytes) of heap memory
Scaling row group sizes to 76.00% for 10 writers
24/11/04 13:59:47 WARN MemoryManager: Total allocation exceeds 95.00% (1,020,054,720 bytes) of heap memory
Scaling row group sizes to 69.09% for 11 writers
24/11/04 13:59:47 WARN MemoryManager: Total allocation exceeds 95.00% (1,020,054,720 bytes) of heap memory
Scaling row group sizes to 76.00% for 10 writers
24/11/04 13:59:47 WARN MemoryManager: Total allocation exceeds 95.00% (1,020,054,720 bytes) of heap memory
Scaling row group sizes to 69.09% for 11 writers
24/11/04 13:59:47 WARN MemoryManager: Total allocation exceeds 95.00% (1,020,054,720 bytes) of heap memory
Scaling row group sizes to 63.33% for 12 writers
24/11/04 13:59:47 WARN MemoryManager: Total allocation exceeds 95.00% (1,020,054,720 bytes) of heap memory
Scaling row group sizes to 58.46% for 13 writers
24/11/04 13:59:47 WARN MemoryManager: Total allocation exceeds 95.00% (1,020,054,720 bytes) of heap memory
Scaling row group sizes to 63.33% for 12 writers
24/11/04 13:59:47 WARN MemoryManager: Total allocation exceeds 95.00% (1,020,054,720 bytes) of heap memory
Scaling row group sizes to 69.09% for 11 writers
24/11/04 13:59:47 WARN MemoryManager: Total allocation exceeds 95.00% (1,020,054,720 bytes) of heap memory
Scaling row group sizes to 76.00% for 10 writers
24/11/04 13:59:47 WARN MemoryManager: Total allocation exceeds 95.00% (1,020,054,720 bytes) of heap memory
Scaling row group sizes to 69.09% for 11 writers
24/11/04 13:59:47 WARN MemoryManager: Total allocation exceeds 95.00% (1,020,054,720 bytes) of heap memory
Scaling row group sizes to 76.00% for 10 writers
24/11/04 13:59:47 WARN MemoryManager: Total allocation exceeds 95.00% (1,020,054,720 bytes) of heap memory
Scaling row group sizes to 84.44% for 9 writers
24/11/04 13:59:47 WARN MemoryManager: Total allocation exceeds 95.00% (1,020,054,720 bytes) of heap memory
Scaling row group sizes to 95.00% for 8 writers
24/11/04 13:59:47 WARN MemoryManager: Total allocation exceeds 95.00% (1,020,054,720 bytes) of heap memory
Scaling row group sizes to 95.00% for 8 writers
24/11/04 13:59:47 WARN MemoryManager: Total allocation exceeds 95.00% (1,020,054,720 bytes) of heap memory
Scaling row group sizes to 84.44% for 9 writers
24/11/04 13:59:47 WARN MemoryManager: Total allocation exceeds 95.00% (1,020,054,720 bytes) of heap memory
Scaling row group sizes to 76.00% for 10 writers
24/11/04 13:59:47 WARN MemoryManager: Total allocation exceeds 95.00% (1,020,054,720 bytes) of heap memory
Scaling row group sizes to 69.09% for 11 writers
24/11/04 13:59:47 WARN MemoryManager: Total allocation exceeds 95.00% (1,020,054,720 bytes) of heap memory
Scaling row group sizes to 63.33% for 12 writers
24/11/04 13:59:47 WARN MemoryManager: Total allocation exceeds 95.00% (1,020,054,720 bytes) of heap memory
Scaling row group sizes to 58.46% for 13 writers
24/11/04 13:59:47 WARN MemoryManager: Total allocation exceeds 95.00% (1,020,054,720 bytes) of heap memory
Scaling row group sizes to 54.29% for 14 writers
24/11/04 13:59:47 WARN MemoryManager: Total allocation exceeds 95.00% (1,020,054,720 bytes) of heap memory
Scaling row group sizes to 50.67% for 15 writers
24/11/04 13:59:47 WARN MemoryManager: Total allocation exceeds 95.00% (1,020,054,720 bytes) of heap memory
Scaling row group sizes to 54.29% for 14 writers
24/11/04 13:59:47 WARN MemoryManager: Total allocation exceeds 95.00% (1,020,054,720 bytes) of heap memory
Scaling row group sizes to 58.46% for 13 writers
24/11/04 13:59:47 WARN MemoryManager: Total allocation exceeds 95.00% (1,020,054,720 bytes) of heap memory
Scaling row group sizes to 54.29% for 14 writers
24/11/04 13:59:47 WARN MemoryManager: Total allocation exceeds 95.00% (1,020,054,720 bytes) of heap memory
Scaling row group sizes to 58.46% for 13 writers
24/11/04 13:59:47 WARN MemoryManager: Total allocation exceeds 95.00% (1,020,054,720 bytes) of heap memory
Scaling row group sizes to 63.33% for 12 writers
24/11/04 13:59:47 WARN MemoryManager: Total allocation exceeds 95.00% (1,020,054,720 bytes) of heap memory
Scaling row group sizes to 58.46% for 13 writers
24/11/04 13:59:47 WARN MemoryManager: Total allocation exceeds 95.00% (1,020,054,720 bytes) of heap memory
Scaling row group sizes to 63.33% for 12 writers
24/11/04 13:59:47 WARN MemoryManager: Total allocation exceeds 95.00% (1,020,054,720 bytes) of heap memory
Scaling row group sizes to 58.46% for 13 writers
24/11/04 13:59:47 WARN MemoryManager: Total allocation exceeds 95.00% (1,020,054,720 bytes) of heap memory
Scaling row group sizes to 63.33% for 12 writers
24/11/04 13:59:47 WARN MemoryManager: Total allocation exceeds 95.00% (1,020,054,720 bytes) of heap memory
Scaling row group sizes to 58.46% for 13 writers
24/11/04 13:59:47 WARN MemoryManager: Total allocation exceeds 95.00% (1,020,054,720 bytes) of heap memory
Scaling row group sizes to 54.29% for 14 writers
24/11/04 13:59:47 WARN MemoryManager: Total allocation exceeds 95.00% (1,020,054,720 bytes) of heap memory
Scaling row group sizes to 50.67% for 15 writers
24/11/04 13:59:47 WARN MemoryManager: Total allocation exceeds 95.00% (1,020,054,720 bytes) of heap memory
Scaling row group sizes to 47.50% for 16 writers
24/11/04 13:59:47 WARN MemoryManager: Total allocation exceeds 95.00% (1,020,054,720 bytes) of heap memory
Scaling row group sizes to 50.67% for 15 writers
24/11/04 13:59:47 WARN MemoryManager: Total allocation exceeds 95.00% (1,020,054,720 bytes) of heap memory
Scaling row group sizes to 54.29% for 14 writers
24/11/04 13:59:47 WARN MemoryManager: Total allocation exceeds 95.00% (1,020,054,720 bytes) of heap memory
Scaling row group sizes to 58.46% for 13 writers
24/11/04 13:59:47 WARN MemoryManager: Total allocation exceeds 95.00% (1,020,054,720 bytes) of heap memory
Scaling row group sizes to 63.33% for 12 writers
24/11/04 13:59:47 WARN MemoryManager: Total allocation exceeds 95.00% (1,020,054,720 bytes) of heap memory
Scaling row group sizes to 69.09% for 11 writers
24/11/04 13:59:47 WARN MemoryManager: Total allocation exceeds 95.00% (1,020,054,720 bytes) of heap memory
Scaling row group sizes to 63.33% for 12 writers
24/11/04 13:59:47 WARN MemoryManager: Total allocation exceeds 95.00% (1,020,054,720 bytes) of heap memory
Scaling row group sizes to 69.09% for 11 writers
24/11/04 13:59:47 WARN MemoryManager: Total allocation exceeds 95.00% (1,020,054,720 bytes) of heap memory
Scaling row group sizes to 76.00% for 10 writers
24/11/04 13:59:47 WARN MemoryManager: Total allocation exceeds 95.00% (1,020,054,720 bytes) of heap memory
Scaling row group sizes to 69.09% for 11 writers
24/11/04 13:59:47 WARN MemoryManager: Total allocation exceeds 95.00% (1,020,054,720 bytes) of heap memory
Scaling row group sizes to 63.33% for 12 writers
24/11/04 13:59:47 WARN MemoryManager: Total allocation exceeds 95.00% (1,020,054,720 bytes) of heap memory
Scaling row group sizes to 58.46% for 13 writers
24/11/04 13:59:47 WARN MemoryManager: Total allocation exceeds 95.00% (1,020,054,720 bytes) of heap memory
Scaling row group sizes to 63.33% for 12 writers
24/11/04 13:59:47 WARN MemoryManager: Total allocation exceeds 95.00% (1,020,054,720 bytes) of heap memory
Scaling row group sizes to 69.09% for 11 writers
24/11/04 13:59:47 WARN MemoryManager: Total allocation exceeds 95.00% (1,020,054,720 bytes) of heap memory
Scaling row group sizes to 63.33% for 12 writers
24/11/04 13:59:47 WARN MemoryManager: Total allocation exceeds 95.00% (1,020,054,720 bytes) of heap memory
Scaling row group sizes to 58.46% for 13 writers
24/11/04 13:59:47 WARN MemoryManager: Total allocation exceeds 95.00% (1,020,054,720 bytes) of heap memory
Scaling row group sizes to 54.29% for 14 writers
24/11/04 13:59:47 WARN MemoryManager: Total allocation exceeds 95.00% (1,020,054,720 bytes) of heap memory
Scaling row group sizes to 58.46% for 13 writers
24/11/04 13:59:47 WARN MemoryManager: Total allocation exceeds 95.00% (1,020,054,720 bytes) of heap memory
Scaling row group sizes to 63.33% for 12 writers
24/11/04 13:59:47 WARN MemoryManager: Total allocation exceeds 95.00% (1,020,054,720 bytes) of heap memory
Scaling row group sizes to 69.09% for 11 writers
24/11/04 13:59:47 WARN MemoryManager: Total allocation exceeds 95.00% (1,020,054,720 bytes) of heap memory
Scaling row group sizes to 76.00% for 10 writers
24/11/04 13:59:47 WARN MemoryManager: Total allocation exceeds 95.00% (1,020,054,720 bytes) of heap memory
Scaling row group sizes to 84.44% for 9 writers
24/11/04 13:59:47 WARN MemoryManager: Total allocation exceeds 95.00% (1,020,054,720 bytes) of heap memory
Scaling row group sizes to 95.00% for 8 writers
24/11/04 13:59:47 WARN MemoryManager: Total allocation exceeds 95.00% (1,020,054,720 bytes) of heap memory
Scaling row group sizes to 95.00% for 8 writers
24/11/04 13:59:47 WARN MemoryManager: Total allocation exceeds 95.00% (1,020,054,720 bytes) of heap memory
Scaling row group sizes to 95.00% for 8 writers
24/11/04 13:59:47 WARN MemoryManager: Total allocation exceeds 95.00% (1,020,054,720 bytes) of heap memory
Scaling row group sizes to 84.44% for 9 writers
24/11/04 13:59:47 WARN MemoryManager: Total allocation exceeds 95.00% (1,020,054,720 bytes) of heap memory
Scaling row group sizes to 76.00% for 10 writers
24/11/04 13:59:47 WARN MemoryManager: Total allocation exceeds 95.00% (1,020,054,720 bytes) of heap memory
Scaling row group sizes to 69.09% for 11 writers
24/11/04 13:59:47 WARN MemoryManager: Total allocation exceeds 95.00% (1,020,054,720 bytes) of heap memory
Scaling row group sizes to 76.00% for 10 writers
24/11/04 13:59:47 WARN MemoryManager: Total allocation exceeds 95.00% (1,020,054,720 bytes) of heap memory
Scaling row group sizes to 69.09% for 11 writers

root
 |-- stationcode: string (nullable = true)
 |-- mean_available: double (nullable = true)
 |-- median_available: long (nullable = true)
 |-- min_available: long (nullable = true)
 |-- max_available: long (nullable = true)
 |-- name: string (nullable = true)

## 4. Update hive metastore

In [7]:
!pip install trino

Requirement already satisfied: trino in /opt/conda/lib/python3.9/site-packages (0.330.0)
Requirement already satisfied: python-dateutil in /opt/conda/lib/python3.9/site-packages (from trino) (2.8.2)
Requirement already satisfied: pytz in /opt/conda/lib/python3.9/site-packages (from trino) (2021.3)
Requirement already satisfied: requests>=2.31.0 in /opt/conda/lib/python3.9/site-packages (from trino) (2.32.3)
Requirement already satisfied: tzlocal in /opt/conda/lib/python3.9/site-packages (from trino) (5.2)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/conda/lib/python3.9/site-packages (from requests>=2.31.0->trino) (1.26.7)
Requirement already satisfied: charset-normalizer<4,>=2 in /opt/conda/lib/python3.9/site-packages (from requests>=2.31.0->trino) (2.0.0)
Requirement already satisfied: certifi>=2017.4.17 in /opt/conda/lib/python3.9/site-packages (from requests>=2.31.0->trino) (2021.10.8)
Requirement already satisfied: idna<4,>=2.5 in /opt/conda/lib/python3.9/site-packages (from requests>=2.31.0->trino) (3.1)
Requirement already satisfied: six>=1.5 in /opt/conda/lib/python3.9/site-packages (from python-dateutil->trino) (1.16.0)

In [8]:
import trino
from pyspark.sql import functions as F
from pyspark.sql.window import Window
 
# Connection
def get_trino_connection():
    host, port, user = 'trino-coordinator', 8080, 'trino'
    return trino.dbapi.connect(host=host, port=port, user=user)
 
# Schémas des tables
velib_turnover = f"""
    date VARCHAR,
    total_arrivals BIGINT,
    total_departures BIGINT,
    total_turnover_rate BIGINT,
    station_capacity BIGINT,
    station_name VARCHAR,
    numbikesavailable BIGINT,
    hour_start TIMESTAMP
"""

velib_stats = f"""
    mean_available DOUBLE,
    median_available DOUBLE,
    min_available BIGINT,
    max_available BIGINT,
    hour_start TIMESTAMP
"""
    
velib_stats_station = f"""
    stationcode VARCHAR,
    mean_available DOUBLE,
    median_available BIGINT,
    min_available BIGINT,
    max_available BIGINT,
    name VARCHAR
"""

 
# Création de la table Trino
def create_trino_table(catalog, schema_name, table, schema, partitioned_by, external_location):
    conn = get_trino_connection()
    cur = conn.cursor()
    queries = [
        f"CREATE SCHEMA IF NOT EXISTS {catalog}.{schema_name} WITH (location = '{external_location}')",
        f"DROP TABLE IF EXISTS {catalog}.{schema_name}.{table}",
        f"""
        CREATE TABLE IF NOT EXISTS {catalog}.{schema_name}.{table} (
        {schema}
        )
        WITH (
            format = 'PARQUET',
            partitioned_by = ARRAY['{partitioned_by}'],
            external_location = '{external_location}'
        )
        """,
        f"CALL {catalog}.system.sync_partition_metadata('{schema_name}', '{table}', 'ADD')",
        f"SELECT * FROM {catalog}.{schema_name}.{table} LIMIT 5"
    ]
    for query in queries:
        try:
            cur.execute(query)
            if query.startswith("SELECT"):
                results = cur.fetchall()
                for row in results:
                    print(row)
            else:
                print(f"Executed: {query}")
        except Exception as e:
            print(f"Error executing query: {query}. Error: {e}")
    cur.close()
    conn.close()

output_path = 's3a://velib/gold/velib-disponibilite-en-temps-reel'
 
# Appel de la fonction avec les schémas
create_trino_table('minio', 'velib_gold_turnover', 'velib_disponibilite_turnover', velib_turnover, 'hour_start',  f"{output_path}/turnover")
create_trino_table('minio', 'velib_gold_stats', 'velib_disponibilite_stats', velib_stats, 'hour_start',  f"{output_path}/stats_global")
create_trino_table('minio', 'velib_gold_stats_station', 'velib_disponibilite_stats_station', velib_stats_station, 'name', f"{output_path}/stats_station")

Executed: CREATE SCHEMA IF NOT EXISTS minio.velib_gold_turnover WITH (location = 's3a://velib/gold/velib-disponibilite-en-temps-reel/turnover')
Executed: DROP TABLE IF EXISTS minio.velib_gold_turnover.velib_disponibilite_turnover
Executed:
        CREATE TABLE IF NOT EXISTS minio.velib_gold_turnover.velib_disponibilite_turnover (

    date VARCHAR,
    total_arrivals BIGINT,
    total_departures BIGINT,
    total_turnover_rate BIGINT,
    station_capacity BIGINT,
    station_name VARCHAR,
    numbikesavailable BIGINT,
    hour_start TIMESTAMP

        )
        WITH (
            format = 'PARQUET',
            partitioned_by = ARRAY['hour_start'],
            external_location = 's3a://velib/gold/velib-disponibilite-en-temps-reel/turnover'
        )

Executed: CALL minio.system.sync_partition_metadata('velib_gold_turnover', 'velib_disponibilite_turnover', 'ADD')
['2024-10-31', 16, 13, 29, 35, 'Gare de Bercy', 21, datetime.datetime(2024, 10, 31, 10, 0)]
['2024-10-31', 5, 5, 10, 23, 'Véron - Lepic', 2, datetime.datetime(2024, 10, 31, 7, 0)]
['2024-10-31', 7, 0, 7, 23, 'Roquette - Thiéré', 15, datetime.datetime(2024, 10, 31, 11, 0)]
['2024-10-31', 5, 7, 12, 39, 'Odessa - Départ', 3, datetime.datetime(2024, 10, 31, 8, 0)]
['2024-10-31', 47, 39, 86, 32, 'Les Halles - Saint-Eustache', 17, datetime.datetime(2024, 10, 31, 10, 0)]
Executed: CREATE SCHEMA IF NOT EXISTS minio.velib_gold_stats WITH (location = 's3a://velib/gold/velib-disponibilite-en-temps-reel/stats_global')
Executed: DROP TABLE IF EXISTS minio.velib_gold_stats.velib_disponibilite_stats
Executed:
        CREATE TABLE IF NOT EXISTS minio.velib_gold_stats.velib_disponibilite_stats (

    mean_available DOUBLE,
    median_available DOUBLE,
    min_available BIGINT,
    max_available BIGINT,
    hour_start TIMESTAMP

        )
        WITH (
            format = 'PARQUET',
            partitioned_by = ARRAY['hour_start'],
            external_location = 's3a://velib/gold/velib-disponibilite-en-temps-reel/stats_global'
        )

Executed: CALL minio.system.sync_partition_metadata('velib_gold_stats', 'velib_disponibilite_stats', 'ADD')
[10.783098630496852, 7.0, 0, 65, datetime.datetime(2024, 10, 31, 9, 0)]
[11.571198316581228, 9.0, 0, 65, datetime.datetime(2024, 10, 31, 7, 0)]
[3.662613981762918, 2.0, 0, 20, datetime.datetime(2024, 10, 31, 8, 0)]
[0.3225806451612903, 0.0, 0, 1, datetime.datetime(2024, 10, 31, 6, 0)]
[12.17424872861766, 8.0, 0, 66, datetime.datetime(2024, 10, 31, 13, 0)]
Executed: CREATE SCHEMA IF NOT EXISTS minio.velib_gold_stats_station WITH (location = 's3a://velib/gold/velib-disponibilite-en-temps-reel/stats_station')
Executed: DROP TABLE IF EXISTS minio.velib_gold_stats_station.velib_disponibilite_stats_station
Executed:
        CREATE TABLE IF NOT EXISTS minio.velib_gold_stats_station.velib_disponibilite_stats_station (

    stationcode VARCHAR,
    mean_available DOUBLE,
    median_available BIGINT,
    min_available BIGINT,
    max_available BIGINT,
    name VARCHAR

        )
        WITH (
            format = 'PARQUET',
            partitioned_by = ARRAY['name'],
            external_location = 's3a://velib/gold/velib-disponibilite-en-temps-reel/stats_station'
        )

Executed: CALL minio.system.sync_partition_metadata('velib_gold_stats_station', 'velib_disponibilite_stats_station', 'ADD')
['10162', 1.8, 1, 1, 4, 'Alexandre Parodi - Quai de Valmy']
['13009', 3.9516129032258065, 2, 2, 7, 'Auguste Blanqui - Corvisart']
['2101', 17.303030303030305, 17, 15, 18, 'Bachaumont - Montmartre']
['20013', 4.0, 4, 4, 4, 'Alexandre Dumas - Place de la Réunion']
['2101', 8.096774193548388, 6, 6, 18, 'Bachaumont - Montmartre']